FROM ghcr.io/mythicagents/athena:main

# #FROM itsafeaturemythic/mythic_base_image:0.0.1
# FROM itsafeaturemythic/mythic_python_dotnet:latest

# COPY ["requirements.txt", "/requirements.txt"]
# RUN python3 -m pip install -r /requirements.txt
# RUN apt-get update && apt-get install -y powershell
# RUN dotnet tool install Obfuscar.GlobalTool -g
# WORKDIR /Mythic/
# CMD ["python3", "main.py"]