name: Agent Builds

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        dotnet-quality: preview

    - name: Build Agent
      run: dotnet publish Payload_Type/athena/athena/agent_code/Workflow.sln -c LocalDebugHttp --nologo -v q --property WarningLevel=0 /clp:ErrorsOnly

  workflow-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        dotnet-quality: preview

    - name: Build and test
      timeout-minutes: 5
      run: dotnet test Payload_Type/athena/athena/agent_code/Tests/Workflow.Tests/Workflow.Tests.csproj -c Debug --nologo --blame-hang --blame-hang-timeout 30s --logger "console;verbosity=detailed" --logger "trx;LogFileName=results.trx"

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.os }}
        path: '**/results.trx'
        retention-days: 7
